name = "main"
position = "top"
height = 18
start_hidden = true
popup_autohide = true
exclusive_zone = true

[[start]]
type = "script"
cmd = "$HOME/.config/ironbar/scripts/workspaces.sh"
mode = "watch"
class = "workspaces-widget"
tooltip = "Workspaces"

[[start]]
type = "focused"
show_icon = false
truncate.mode = "end"
truncate.max_length = 28
tooltip = "Focused Window"

[[start]]
type = "script"
cmd = "$HOME/.config/ironbar/scripts/winfloat.sh"
mode = "watch"
class = "winfloat"
tooltip = "Window Layout Status"

[[center]]
type = "clock"
format = "%I:%M %p"
format_popup = "%A, %d %B %Y"
tooltip = "Calendar"

[[end]]
type = "music"
format = "{title}"
show_status_icon = true
truncate.mode = "end"
truncate.max_length = 28
icons.play = "▶"
icons.pause = "⏸"
icons.prev = "⏮"
icons.next = "⏭"
icons.volume = ""
icons.track = "🎵"
icons.album = "💿"
icons.artist = "🎤"
on_click_left = "playerctl play-pause"
on_click_right = "playerctl next"
on_click_middle = "playerctl previous"
on_scroll_up = "playerctl volume 0.05+"
on_scroll_down = "playerctl volume 0.05-"
tooltip = "Media Controls"

[[end]]
type = "script"
class = "caffeine"
cmd = "/home/mishal/.config/ironbar/scripts/caffeine.sh"
mode = "poll"
interval = 2
on_click_left = "/home/mishal/.config/ironbar/scripts/caffeine-toggle.sh"
tooltip = "Caffeine: toggle sleep"

[[end]]
type = "script"
class = "network"
cmd = "$HOME/.config/ironbar/scripts/net.sh"
mode = "watch"
on_click_left = "$HOME/.config/ironbar/scripts/network-info.sh"
on_click_right = "$HOME/.config/ironbar/scripts/wifi-toggle.sh"
tooltip = "Network"

[[end]]
type = "bluetooth"
icon_size = 32
on_click_right = "$HOME/.config/ironbar/scripts/bluetooth-toggle.sh"
tooltip = "Bluetooth Settings"

[end.format]
not_found = ""
disabled = ""
enabled = ""
connected = ""
connected_battery = " {device_battery_percent}%"

[end.device_status]
connected = ""
connecting = ""
disconnected = ""
disconnecting = ""

[[end]]
type = "volume"
format = "{icon} {percentage}%"
icons.muted = ""
icons.volume_low = ""
icons.volume_medium = ""
icons.volume_high = ""
on_click_right = "$HOME/.config/ironbar/scripts/audio-next.sh"
show_sources = false
popup_orientation = "horizontal"
sink_slider_orientation = "horizontal"
tooltip = "Volume Controls"

[[end]]
type = "script"
class = "brightness"
cmd = "$HOME/.config/ironbar/scripts/brightness.sh"
mode = "watch"
on_click_left = "$HOME/.config/ironbar/scripts/brightness-menu.sh"
on_scroll_up = "$HOME/.config/ironbar/scripts/brightness-step.sh up"
on_scroll_down = "$HOME/.config/ironbar/scripts/brightness-step.sh down"
tooltip = "Brightness"

[[end]]
type = "script"
class = "battery"
cmd = "$HOME/.config/ironbar/scripts/battery.sh"
mode = "watch"
tooltip = "Battery Status"

[[end]]
type = "script"
class = "power"
cmd = "echo '  '"
mode = "watch"
on_click_left = "$HOME/.config/ironbar/scripts/power.sh"
tooltip = "Lock Screen"