wireplumber.settings = {
  default-policy.move-streams-on-default-node-changes = true
  default-policy.use-persistent-storage = true
}

monitor.bluez.rules = [
  {
    matches = [
      { node.name = "~bluez_output.*" }
    ]
    actions = {
      update-props = {
        priority.session = 2000
        node.autoconnect  = true
      }
    }
  }
  {
    matches = [
      { node.name = "~bluez_input.*" }
    ]
    actions = {
      update-props = {
        priority.session = 2000
        node.autoconnect  = true
      }
    }
  }
]
