# Allow the audio device to suspend when idle to save battery.
monitor.alsa.rules = [
  {
    matches = [
      { device.name = "alsa_card.pci-0000_00_0e.0" }
    ]
    actions = {
      update-props = {
        node.pause-on-idle = true
        session.suspend-timeout-seconds = 10
      }
    }
  }
]
